import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@rainbow-me/rainbowkit/styles.css';
import { RainbowkitAndWagmiProviders } from './utils/RainbowkitAndWagmiProviders';
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ChakraProvider } from "@chakra-ui/react";
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${inter.className} bg-bcolor`}>
        <ChakraProvider>
          <RainbowkitAndWagmiProviders>
          <Header/>
          { children }
          <Footer/>
        </RainbowkitAndWagmiProviders>
        <Toaster />
       </ChakraProvider> 
      </body>
  
    </html>
  );
}
