name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Check changed files
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff-tree --name-only HEAD^ HEAD)
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Bump version and publish
        if: ${{ steps.check_changes.outputs.changed_files != 'apps' && steps.check_changes.outputs.changed_files != 'bin'}}
        run: |
          npm version patch --no-git-tag-version
          git push origin master --follow-tags
          npm publish
